#!/bin/bash

systemctl stop lifestuff-mgr.service
rm /etc/systemd/system/lifestuff-mgr.service
systemctl daemon-reload

size=`du -s  /home/lifestuff/ |  awk '{print $1}'`
if [ $size -lt 100 ] ; then
  userdel lifestuff
  rm -r /home/lifestuff
fi
