#!/bin/bash
#  allowing lifestuff to be put in systray
tray_list=`gsettings get com.canonical.Unity.Panel systray-whitelist`
all_exists=`echo $tray_list | grep "'all'" | wc -l`
lifestuff_exists=`echo $tray_list | grep "'lifestuff'" | wc -l`
if [ $lifestuff_exists -eq 0 ] && [ $all_exists -eq 0 ] ; then
  tray_list=`echo $tray_list | sed "s|[]]|, \'lifestuff']|"`
  `gsettings set com.canonical.Unity.Panel systray-whitelist "${tray_list}"`
fi

#create user lifestuff if does not exist
if [ -z $(getent passwd lifestuff) ]
then
  echo user does not exists
  useradd -m -s /usr/sbin/nologin lifestuff
fi

/usr/sbin/update-rc.d lifestuff-mgr defaults
/etc/init.d/lifestuff-mgr start
