#!/bin/bash
/etc/init.d/lifestuff-mgr stop
/usr/sbin/update-rc.d -f lifestuff-mgr remove

#removing lifestuff from systray allowed applications
tray_list=`gsettings get com.canonical.Unity.Panel systray-whitelist`
tray_list=`echo $tray_list|sed s/.$//`
tray_list=`echo $tray_list|sed s/.//`
tray_list=`echo $tray_list| sed s/,/\/g`
new_try=""
for item in ${tray_list}
do
  lifestuff_exists=`echo $item | grep "'lifestuff'" | wc -l`
  if [ $lifestuff_exists -eq 0 ] ; then
    if [ "${new_tray}" != "" ] ; then
      new_tray=${new_tray}","
    fi
    new_tray=${new_tray}" "${item}
  fi
done
new_tray="["${new_tray}"]"
`gsettings set com.canonical.Unity.Panel systray-whitelist "${new_tray}"`

size=`du -s  /home/lifestuff/ |  awk '{print $1}'`
if [ $size -lt 100 ] ; then
  deluser lifestuff
  rm -r /home/lifestuff
fi
