#!/bin/bash

# Copy the configuration .plist file to the LaunchDaemons directory
cp /Applications/LifeStuff.app/Contents/Resources/com.lifestuff.invigilator.plist /Library/LaunchDaemons/
cp /Applications/LifeStuff.app/Contents/Resources/com.lifestuff.invigilator-checker.plist /Library/LaunchDaemons/
cp /Applications/LifeStuff.app/Contents/Resources/invigilator-checker /usr/local/bin/

# Check if lifestuff user exists, if not create it
if id -u lifestuff >/dev/null 2>&1; then
   echo "User exists!"
else
   echo "User does not exist! Creating new user!"
   dscl . -create /Users/lifestuff
fi

# Launch the daemon 
launchctl load -w /Library/LaunchDaemons/com.lifestuff.invigilator.plist
launchctl load -w /Library/LaunchDaemons/com.lifestuff.invigilator-checker.plist
